version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: python3 -m venv venv
      - run:
          name: Install requirements and run build script
          command: |
            . venv/bin/activate
            pip install --requirement requirements.txt
            pip install --requirement dev_requirements.txt
            ./build
  e2e:
    machine:
      - image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Install TinyPilot
          command: ./quick-install
      # TODO: Check that TinyPilot's web interface is up and running.
workflows:
  test:
    jobs:
      - build
      - e2e
